/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ngoni
 */
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;

    public admin() {
        super("Admin");
        initComponents();
        conn = dataBaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textLabel = new javax.swing.JLabel();
        textLabel1 = new javax.swing.JLabel();
        textLabel2 = new javax.swing.JLabel();
        adminName = new javax.swing.JTextField();
        adminUserName = new javax.swing.JTextField();
        adminPassword = new javax.swing.JPasswordField();
        adminUpdate = new javax.swing.JButton();
        adminBack = new javax.swing.JButton();
        adminSearch = new javax.swing.JButton();
        adminDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adminID = new javax.swing.JTextField();
        adminClear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        homeMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Admins", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(0, 153, 204))); // NOI18N

        textLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textLabel.setForeground(new java.awt.Color(0, 153, 204));
        textLabel.setText("Name");

        textLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textLabel1.setForeground(new java.awt.Color(0, 153, 204));
        textLabel1.setText("Username");

        textLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textLabel2.setForeground(new java.awt.Color(0, 153, 204));
        textLabel2.setText("Password");

        adminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameActionPerformed(evt);
            }
        });

        adminUpdate.setBackground(new java.awt.Color(0, 0, 0));
        adminUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        adminUpdate.setForeground(new java.awt.Color(0, 153, 204));
        adminUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png files/submit.png"))); // NOI18N
        adminUpdate.setText("Update");
        adminUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUpdateActionPerformed(evt);
            }
        });

        adminBack.setBackground(new java.awt.Color(0, 0, 0));
        adminBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        adminBack.setForeground(new java.awt.Color(0, 153, 204));
        adminBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png files/back.png"))); // NOI18N
        adminBack.setText("Back");
        adminBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBackActionPerformed(evt);
            }
        });

        adminSearch.setBackground(new java.awt.Color(0, 0, 0));
        adminSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        adminSearch.setForeground(new java.awt.Color(0, 153, 204));
        adminSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png files/loupe.png"))); // NOI18N
        adminSearch.setText("Search");
        adminSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSearchActionPerformed(evt);
            }
        });

        adminDelete.setBackground(new java.awt.Color(0, 0, 0));
        adminDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        adminDelete.setForeground(new java.awt.Color(0, 153, 204));
        adminDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png files/cancel1.png"))); // NOI18N
        adminDelete.setText("Delete");
        adminDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Admin ID");

        adminID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminIDActionPerformed(evt);
            }
        });
        adminID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminIDKeyPressed(evt);
            }
        });

        adminClear.setBackground(new java.awt.Color(0, 0, 0));
        adminClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        adminClear.setForeground(new java.awt.Color(0, 153, 204));
        adminClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png files/clear.png"))); // NOI18N
        adminClear.setText("Clear");
        adminClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textLabel)
                    .addComponent(textLabel1)
                    .addComponent(textLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adminUpdate)
                        .addGap(30, 30, 30)
                        .addComponent(adminDelete))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(adminID, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addComponent(adminName)
                        .addComponent(adminUserName)
                        .addComponent(adminPassword)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adminBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adminSearch)
                        .addGap(26, 26, 26)
                        .addComponent(adminClear)
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminSearch)
                    .addComponent(adminClear))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLabel))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel1)
                    .addComponent(adminUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDelete)
                    .addComponent(adminBack)
                    .addComponent(adminUpdate))
                .addGap(32, 32, 32))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png files/home.png"))); // NOI18N

        homeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        homeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png files/home.png"))); // NOI18N
        homeMenuItem.setText("Home");
        homeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(homeMenuItem);

        logoutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png files/logout.png"))); // NOI18N
        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(614, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //TO BE IGNNORED!!!!!
    private void adminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameActionPerformed
        
    }//GEN-LAST:event_adminNameActionPerformed

    private void adminUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUpdateActionPerformed
        
        try {
            stmt = conn.createStatement();
            int ID = Integer.parseInt(adminID.getText());
            String AdminName = adminName.getText();
            String userName = adminUserName.getText();
            String adminPass = adminPassword.getText();

            String sql = "UPDATE  ADMIN SET user_Name = '" + userName + "', password = '" + adminPass + "', admin_Name = '" + AdminName + "'WHERE ID = '" + ID + "'";

            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is successfully saved");
            clearAdmin();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_adminUpdateActionPerformed

    private void clearAdmin() {
        adminID.setText(null);
        adminName.setText(null);
        adminUserName.setText(null);
        adminPassword.setText(null);
    }

    private void clearAdminSettings() { 
        adminName.setText(null);
        adminUserName.setText(null);
        adminPassword.setText(null);
    }

    private void adminBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBackActionPerformed
        
        setVisible(false);
        home obj = new home();
        obj.setVisible(true);
    }//GEN-LAST:event_adminBackActionPerformed

    private void adminSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSearchActionPerformed
        
        try {
            stmt = conn.createStatement();

            int ID = Integer.parseInt(adminID.getText());

            String sql = "SELECT * FROM ADMIN WHERE ID='" + ID + "'";

            rs = stmt.executeQuery(sql);
            if (rs.next()) {
                adminName.setText(rs.getString("admin_name"));
                adminPassword.setText(rs.getString("password"));
                adminUserName.setText(rs.getString("user_name"));
            } else {
                JOptionPane.showMessageDialog(null, "Record not found");
                clearAdminSettings();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_adminSearchActionPerformed

    //TO BE IGNNORED!!!!!
    private void adminIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminIDActionPerformed
        
    }//GEN-LAST:event_adminIDActionPerformed

    private void adminDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDeleteActionPerformed
        
        try {
            stmt = conn.createStatement();

            int ID = Integer.parseInt(adminID.getText());

            String sql = "DELETE FROM ADMIN WHERE ID = '" + ID + "'";

            stmt.executeUpdate(sql);

            setVisible(false);
            showAdmin obj = new showAdmin();
            obj.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_adminDeleteActionPerformed

    private void homeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuItemActionPerformed
        
        setVisible(false);
        home obj = new home();
        obj.setVisible(true);
    }//GEN-LAST:event_homeMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        
        setVisible(false);
        login obj = new login();
        obj.setVisible(true);

    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void adminIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminIDKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                stmt = conn.createStatement();

                int ID = Integer.parseInt(adminID.getText());

                String sql = "SELECT * FROM ADMIN WHERE ID='" + ID + "'";

                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    adminName.setText(rs.getString("admin_name"));
                    adminPassword.setText(rs.getString("password"));
                    adminUserName.setText(rs.getString("user_name"));
                } else {
                    JOptionPane.showMessageDialog(null, "Record not found");
                    clearAdminSettings();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_adminIDKeyPressed

    private void adminClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminClearActionPerformed
        
        adminID.setText(null);
        adminName.setText(null);
        adminUserName.setText(null);
        adminPassword.setText(null);
    }//GEN-LAST:event_adminClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBack;
    private javax.swing.JButton adminClear;
    private javax.swing.JButton adminDelete;
    private javax.swing.JTextField adminID;
    private javax.swing.JTextField adminName;
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JButton adminSearch;
    private javax.swing.JButton adminUpdate;
    private javax.swing.JTextField adminUserName;
    private javax.swing.JMenuItem homeMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JLabel textLabel;
    private javax.swing.JLabel textLabel1;
    private javax.swing.JLabel textLabel2;
    // End of variables declaration//GEN-END:variables
}
